pr_commands = ["/agentic_describe", "/agentic_review"]

[jira]
jira_base_url = "https://qodo-ai.atlassian.net/"

[review_agent]
comments_location_policy = 'both'  
inline_comments_severity_threshold = 3
